### ISSUE TITLE
Something Went Wrong - Enter the Correct API URL

### ISSUE THREAD

**Issue by YiffyC** [mcnaveen/Random-Words-API#19]
Dear Dev,

Firstly, thanks for your work on this API. 

Since today, I have thie error when calling the API : "Something Went Wrong - Enter the Correct API URL". It occurs when I call from my javascript or Postman, and event in Firefox Browser directly. Everything was working fine prior today.

I hop you have any advice to fix the situation
Thank you by advance,
Regards

![image](https://user-images.githubusercontent.com/22780248/114220048-c6c0b300-996b-11eb-95ec-c2967c0e1d1f.png)
![image](https://user-images.githubusercontent.com/22780248/114220082-d213de80-996b-11eb-8180-227c666f5460.png)

**Comment by mcnaveen** [comment]
Hey, @YiffyC 

I'm really sorry for the trouble happened to you.

I'm aware of this issue, This is due to some dependency updates.

Now fixed, Up and Running.

`https://random-words-api.vercel.app/word`

![image](https://user-images.githubusercontent.com/8493007/114224920-57f55100-998f-11eb-9ebb-8c8d8dd49639.png)

I'm gonna close this issue. Feel free to Reopen if you still face this issue.

Thanks :heart:
