### ISSUE TITLE
API is not working

### ISSUE THREAD

**Issue by nnagewad** [mcnaveen/Random-Words-API#97]
Fetching the URL: `https://random-words-api.vercel.app/word` and I've been getting the following message:
"Something Went Wrong - Enter the Correct API URL"

Just wondering if there is a request limit or if it went down?

**Comment by mcnaveen** [comment]
Hi @nnagewad 

Thanks for creating a issue for this.

Everything seems to be working on my end. Can you try refreshing or check in Incognito.

Also, I suggest you to selfhost. 

And there are no rate limiting applied. 

![Screenshot_20221201-082341~2.png](https://user-images.githubusercontent.com/8493007/204955420-ef69f1dd-b5b9-439b-97d8-1b952f879f6a.png)

**Comment by scrapitt** [comment]
Same error here.

**Comment by mcnaveen** [comment]
@scrapitt Are you hosting it yourself?

**Comment by mskian** [comment]
@scrapitt This method is not working due to Cloudflare 
it may work on localhost but not on Servers

4 options

1 - Use a Residential Proxy
2 - use Headless CMS puppeteer instead of Axios  (For puppeteer VPS Recommended)
3 - use PHP `preg_match` to scrape the data 

```php

  if (preg_match('/<div id="random_word">(.+?)<\/div>/s', $html, $word_match)) {
        $word = trim($word_match[1]);
        $wordOfDay['word'] = ucfirst($word);
    }

    if (preg_match('/<div id="random_word_definition">(.+?)<\/div>/s', $html, $definition_match)) {
        $definition = trim($definition_match[1]);
        $wordOfDay['definition'] = ucfirst($definition);
    }

````

4 - Run on localhost and Store all scraped data in the database locally Later use it on production with the stored data as JSON API
